/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Category = IDL.Variant({
  'realLife' : IDL.Null,
  'scifi' : IDL.Null,
  'motivation' : IDL.Null,
  'comedy' : IDL.Null,
  'horror' : IDL.Null,
  'romance' : IDL.Null,
});
export const StoryMetadata = IDL.Record({
  'id' : IDL.Text,
  'coverImageUrl' : IDL.Text,
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'isSaved' : IDL.Bool,
  'likeCount' : IDL.Nat,
  'published' : IDL.Bool,
  'description' : IDL.Text,
  'audioFilePath' : IDL.Text,
  'creatorName' : IDL.Text,
  'viewCount' : IDL.Nat,
  'category' : Category,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'profilePictureUrl' : IDL.Text,
});
export const AIGeneratedStory = IDL.Record({
  'title' : IDL.Text,
  'body' : IDL.Text,
  'tone' : IDL.Text,
  'description' : IDL.Text,
  'genre' : IDL.Text,
});
export const StoryDraft = IDL.Record({
  'id' : IDL.Text,
  'author' : IDL.Principal,
  'draft' : AIGeneratedStory,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'generateAIDraftStory' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'getAllStories' : IDL.Func([], [IDL.Vec(StoryMetadata)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDraftStory' : IDL.Func([], [IDL.Opt(StoryDraft)], ['query']),
  'getStoriesByCategory' : IDL.Func(
      [Category],
      [IDL.Vec(StoryMetadata)],
      ['query'],
    ),
  'getTrendingStories' : IDL.Func(
      [IDL.Opt(IDL.Nat)],
      [IDL.Vec(StoryMetadata)],
      ['query'],
    ),
  'getUserLikedStories' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getUserSavedStories' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getUserStories' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(StoryMetadata)],
      ['query'],
    ),
  'incrementStoryViews' : IDL.Func([IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeStory' : IDL.Func([IDL.Text], [], []),
  'saveAudioBlob' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveStory' : IDL.Func([StoryMetadata], [], []),
  'saveStoryToLibrary' : IDL.Func([IDL.Text], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStories' : IDL.Func([IDL.Text], [IDL.Vec(StoryMetadata)], ['query']),
  'unlikeStory' : IDL.Func([IDL.Text], [], []),
  'unsaveStoryFromLibrary' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Category = IDL.Variant({
    'realLife' : IDL.Null,
    'scifi' : IDL.Null,
    'motivation' : IDL.Null,
    'comedy' : IDL.Null,
    'horror' : IDL.Null,
    'romance' : IDL.Null,
  });
  const StoryMetadata = IDL.Record({
    'id' : IDL.Text,
    'coverImageUrl' : IDL.Text,
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'isSaved' : IDL.Bool,
    'likeCount' : IDL.Nat,
    'published' : IDL.Bool,
    'description' : IDL.Text,
    'audioFilePath' : IDL.Text,
    'creatorName' : IDL.Text,
    'viewCount' : IDL.Nat,
    'category' : Category,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'profilePictureUrl' : IDL.Text,
  });
  const AIGeneratedStory = IDL.Record({
    'title' : IDL.Text,
    'body' : IDL.Text,
    'tone' : IDL.Text,
    'description' : IDL.Text,
    'genre' : IDL.Text,
  });
  const StoryDraft = IDL.Record({
    'id' : IDL.Text,
    'author' : IDL.Principal,
    'draft' : AIGeneratedStory,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'generateAIDraftStory' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'getAllStories' : IDL.Func([], [IDL.Vec(StoryMetadata)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDraftStory' : IDL.Func([], [IDL.Opt(StoryDraft)], ['query']),
    'getStoriesByCategory' : IDL.Func(
        [Category],
        [IDL.Vec(StoryMetadata)],
        ['query'],
      ),
    'getTrendingStories' : IDL.Func(
        [IDL.Opt(IDL.Nat)],
        [IDL.Vec(StoryMetadata)],
        ['query'],
      ),
    'getUserLikedStories' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getUserSavedStories' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getUserStories' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(StoryMetadata)],
        ['query'],
      ),
    'incrementStoryViews' : IDL.Func([IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeStory' : IDL.Func([IDL.Text], [], []),
    'saveAudioBlob' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveStory' : IDL.Func([StoryMetadata], [], []),
    'saveStoryToLibrary' : IDL.Func([IDL.Text], [], []),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStories' : IDL.Func([IDL.Text], [IDL.Vec(StoryMetadata)], ['query']),
    'unlikeStory' : IDL.Func([IDL.Text], [], []),
    'unsaveStoryFromLibrary' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };