/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AIGeneratedStory {
  'title' : string,
  'body' : string,
  'tone' : string,
  'description' : string,
  'genre' : string,
}
export type Category = { 'realLife' : null } |
  { 'scifi' : null } |
  { 'motivation' : null } |
  { 'comedy' : null } |
  { 'horror' : null } |
  { 'romance' : null };
export type ExternalBlob = Uint8Array;
export interface StoryDraft {
  'id' : string,
  'author' : Principal,
  'draft' : AIGeneratedStory,
}
export interface StoryMetadata {
  'id' : string,
  'coverImageUrl' : string,
  'title' : string,
  'creator' : Principal,
  'isSaved' : boolean,
  'likeCount' : bigint,
  'published' : boolean,
  'description' : string,
  'audioFilePath' : string,
  'creatorName' : string,
  'viewCount' : bigint,
  'category' : Category,
}
export interface UserProfile {
  'bio' : string,
  'username' : string,
  'profilePictureUrl' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'generateAIDraftStory' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'getAllStories' : ActorMethod<[], Array<StoryMetadata>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Only the owner of the draft may retrieve it.
   */
  'getDraftStory' : ActorMethod<[], [] | [StoryDraft]>,
  'getStoriesByCategory' : ActorMethod<[Category], Array<StoryMetadata>>,
  'getTrendingStories' : ActorMethod<[[] | [bigint]], Array<StoryMetadata>>,
  /**
   * / Only the owner or an admin may see their liked stories list.
   */
  'getUserLikedStories' : ActorMethod<[Principal], Array<string>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  /**
   * / Only the owner or an admin may see their saved stories list.
   */
  'getUserSavedStories' : ActorMethod<[Principal], Array<string>>,
  'getUserStories' : ActorMethod<[Principal], Array<StoryMetadata>>,
  /**
   * / Increment view count. Any caller (including guests) can trigger this.
   */
  'incrementStoryViews' : ActorMethod<[string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeStory' : ActorMethod<[string], undefined>,
  /**
   * / Upload the audio blob for a story. Only the story creator may do this.
   */
  'saveAudioBlob' : ActorMethod<[string, ExternalBlob], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Create or update a story. The caller must be the story's creator.
   */
  'saveStory' : ActorMethod<[StoryMetadata], undefined>,
  'saveStoryToLibrary' : ActorMethod<[string], undefined>,
  'saveUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchStories' : ActorMethod<[string], Array<StoryMetadata>>,
  'unlikeStory' : ActorMethod<[string], undefined>,
  'unsaveStoryFromLibrary' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];